" {{{ Settings

" General
set filetype syntax confirm
set noautochdir
set scrolloff=7
set showtabline=2
set laststatus=3

" search
set hlsearch incsearch ignorecase smartcase

" split pane
set nosplitright splitbelow

" appearance
set mouse=a
set list listchars=tab:▷▷,trail:␣,nbsp:⍽

" folding
set foldmethod=marker foldlevel=0

" tabs as spaces
set tabstop=4 shiftwidth=4 softtabstop=0 expandtab autoindent

" spellcheck
set spell spelllang=en spellsuggest=best,8

" window
set number relativenumber numberwidth=3
set cursorline cursorcolumn

" }}}

" {{{ Colorscheme

colo lunaperche

" }}}

" {{{ VimPlug

let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin()
Plug 'junegunn/goyo.vim' " focus mode
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim' " fuzzy finder
call plug#end()

" }}}

" {{{ Keybinds

" leader
nnoremap <SPACE> <NOP>
let mapleader=' '

" autopair
inoremap ( ()<LEFT>
inoremap [ []<LEFT>
inoremap {<CR> {<CR>}0<C-D><ESC>ko

" split panes
nnoremap <leader>\| :vsplit<CR><C-w>l
nnoremap <leader>- :split<CR><C-w>j
nnoremap <leader>q <C-w>q
nnoremap <leader>h <C-w>h
nnoremap <leader>j <C-w>j
nnoremap <leader>k <C-w>k
nnoremap <leader>l <C-w>l
nnoremap <leader><LEFT> <C-w>10<
nnoremap <leader>RIGHT> <C-w>10>
nnoremap <leader><UP> <C-w>5+
nnoremap <leader><DOWN> <C-w>5-
nnoremap <leader>H <C-w>H
nnoremap <leader>J <C-w>J
nnoremap <leader>L <C-w>L

" buffers
nnoremap <leader>[ :bprevious<CR>
nnoremap <leader>] :bnext<CR>

" autocomplete
inoremap <expr><TAB> pumvisible() ? '<C-n>' : '<TAB>'
inoremap <expr><S-TAB> pumvisible() ? '<C-p>' : '<C-n>'

" fzf - taken from ntrupin/noahvim telescope bindings
nnoremap <leader>ff :Files<CR>
nnoremap <leader>f/ :Lines<CR>
nnoremap <leader>b :Buffers<CR>
nnoremap <leader>fh :Helptags<CR>

" }}}

" {{{ Custom commands

command NoahHTerm botright term
command NoahVTerm vertical botright term

" }}}
