" {{{ Settings

" General
set filetype syntax confirm
set noautochdir
set scrolloff=7
set showtabline=2
set laststatus=3

" search
set hlsearch incsearch ignorecase smartcase

" split pane
set nosplitright splitbelow

" appearance
set mouse=a
set list listchars=tab:▷▷,trail:␣,nbsp:⍽

" folding
set foldmethod=marker foldlevel=0

" tabs as spaces
set tabstop=4 softtabstop=0 expandtab autoindent shiftwidth=4

" spellcheck
set spell spelllang=en spellsuggest=best,8

" window
set number relativenumber numberwidth=3
set cursorline cursorcolumn

" }}}

" {{ Colorscheme
colo murphy
" }}}

" {{{ VimPlug

let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin()
Plug 'junegunn/goyo.vim' " focus mode
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim' " fuzzy finder
call plug#end()

" }}}

" {{{ Keybinds

" leader
nnoremap <SPACE> <NOP>
let mapleader=' '

" fzf - taken from ntrupin/noahvim telescope bindings
nnoremap <leader>ff :Files<CR>
nnoremap <leader>f/ :Lines<CR>
nnoremap <leader>b :Buffers<CR>
nnoremap <leader>fh :Helptags<CR>

" }}}
